import os
import warnings
import argparse

scriptVer = 'Ver 1.0'
if __name__ == '__main__':
    #parse arg
    parser = argparse.ArgumentParser(description=f"Parse ATE test datalogs which are generated by chroma tester. | By Alvin | {scriptVer}")
    parser.add_argument("inFile",
                        type=argparse.FileType('r'),
                        default=sys.stdin,
                        help='test data source file'
                        )
    parser.add_argument("--version",
                        action='version',
                        version=scriptVer
                        )
    parser.add_argument("--fileType",
                        "-t",
                        default='csv',
                        type=str,
                        choices=['csv', 'std', 'txt'],
                        help='test data format'
                        )
    print(parser.parse_args().inFile)

